version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: src/FIAP.Api/Dockerfile
    container_name: fiap-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - fiap-network

  db:
    image: postgres:latest
    container_name: fiap-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fiap-network

  sonarqube:
    image: sonarqube:community
    container_name: fiap-sonarqube
    ports:
      - "9001:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    networks:
      - fiap-network

volumes:
  pgdata:
  sonar_data:
  sonar_extensions:
  sonar_logs:

networks:
  fiap-network:
    driver: bridge
