---
name: REFACTOR
about: Template para refatorações ou débitos técnicos
title: "🧹 [Refactor] - <área/componente>"
labels: refactor
assignees: ''
---

## 🧹 Área a ser refatorada

Ex: Service de autenticação

## 🤔 Motivo

Por que essa parte precisa de refatoração?  
Ex: Código duplicado, baixa legibilidade, responsabilidade mal definida...

## 🛠️ O que será feito

Ex:  
- Substituir lógica por padrão Strategy  
- Extrair classe  
- Remover código morto  

## 📌 Impacto previsto

- [ ] Regras de negócio
- [ ] Interface da API
- [ ] Estrutura de banco de dados
- [ ] Testes existentes
